### ISSUE TITLE
Limit group separator to one single character in Prefs dialog

### ISSUE THREAD

**Issue by matthiasgeiger** [koppor/jabref#177] opened 2016-10-26 11:48 UTC
JabRef version 3.7dev

While investigating JabRef/jabref#2184 I noticed that the keyword separator is stored as a String in the prefs, but using the accessor method just returns the first character:

``` java
    public Character getKeywordDelimiter() {
        return get(KEYWORD_SEPARATOR).charAt(0);
    }
```

(see JabRefPreferences.java)

Prefs dialog for groups should be adjusted that it is only possible to insert a single character as delimiter.

**Comment by kdaud** [comment] 2020-01-15 18:15
Hey, I want to work on this issue. Any description on how to reproduce the bug?

**Comment by koppor** [comment] 2020-01-18 00:35
1. Understand what is meant by "Prefs dialog". 

- Hint 1: "Prefs" is the short form for "preferences.
- Hint 2: Search the docs. You won't find a help page on preferences, but on options
- Hint 3: Start JabRef (e.g., by executing `gradlew run`)

You will find

![grafik](https://user-images.githubusercontent.com/1366654/72655051-bac98980-3992-11ea-8ee6-c05f85dcfbf0.png)

- Hint 4: Use Ctrl+Shift+F in IntelliJ to do a full text search on the code
- Hint 5: Search for "Keyword separator"

(It gets late here, I hope the hints will guide you in the right direction)

**Comment by kdaud** [comment] 2020-01-18 18:24
Thanks @koppor, have started working on this issue and hoping to resolve it!

**Comment by colinldbd** [comment] 2023-10-20 04:59
Hi, I'm a new contributor! And I'm very interested in this issue. Can you assign this issue to me so I can work on it? I'm also reading through the contributing guide and found this in one of the good first issues. I'd like to work on it and give it a go.

Many thanks!

**Comment by koppor** [comment] 2023-10-20 07:39
@colinldbd This is your second issue. Have fun working on it!

**Comment by colinldbd** [comment] 2023-10-22 07:56
> 1. Understand what is meant by "Prefs dialog".
> 
> * Hint 1: "Prefs" is the short form for "preferences.
> * Hint 2: Search the docs. You won't find a help page on preferences, but on options
> * Hint 3: Start JabRef (e.g., by executing `gradlew run`)
> 
> You will find
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/72655051-bac98980-3992-11ea-8ee6-c05f85dcfbf0.png)
> 
> * Hint 4: Use Ctrl+Shift+F in IntelliJ to do a full text search on the code
> * Hint 5: Search for "Keyword separator"
> 
> (It gets late here, I hope the hints will guide you in the right direction)

Hi, while trying to reproduce the problem, I noticed there's already some changes made to the preference panel.

In your screenshot, there's an keyword seperator input box in the Preference->Group, however, in the latest version of the repo, that keyword separator has already been moved to the Preference->Entry instead of being in Preference->Group.

![image](https://github.com/koppor/jabref/assets/16120094/f900fd0c-0e10-4972-9f9d-aff9b5f59986)
![image](https://github.com/koppor/jabref/assets/16120094/3813594f-235c-4a8b-bc55-5c3b11b85c33)

But the documentation for JabRef is still not  updated.
See the documentation for Group:
[Documentation for Group](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups)

<img width="1056" alt="image" src="https://github.com/koppor/jabref/assets/16120094/54d1ec11-9cc2-4ec1-b601-8e02af389874">

I'll still be looking into this issue to see whether the original issue still exists, however maybe we should update our documentation for this?
It's a little bit confusing because the documentation doesn't match the actual current GUI for JabRef.

I see the problem might still exist, but it's moved here:
![image](https://github.com/koppor/jabref/assets/16120094/e3c94490-2f28-4b10-9b1b-31ba92288c19)

I'll look into it further.

Many thanks!

**Comment by colinldbd** [comment] 2023-10-22 11:01
Hi, also I opened a new issue for the documentation dismatch.
[issue##10542](https://github.com/JabRef/jabref/issues/10542)

**Comment by colinldbd** [comment] 2023-10-22 11:47
Hi, @koppor @matthiasgeiger, I've already created a PR about this problem [Limit group separator to one single character in Prefs->Entry Keyword Separator #10543](https://github.com/JabRef/jabref/pull/10543) thank you for assigning it to me.

**Comment by koppor** [comment] 2023-10-22 22:31
> It's a little bit confusing because the documentation doesn't match the actual current GUI for JabRef.

@colinldbd This is a consequence that all of our work in JabRef is volunteering work. We cannot catch up on everything here. We rely on contributors like you. I think, with https://github.com/JabRef/user-documentation/issues/468 you already went half the way. - You could even take that as change to check out the new docuemtation IDE of JetBrains (https://www.jetbrains.com/writerside/)

**Comment by ThiloteE** [comment] 2024-05-20 19:15
I assume this issue was fixed by https://github.com/JabRef/jabref/pull/10543, thereby closing.

**Closed by ThiloteE** 2024-05-20 19:15 UTC
Labels: feature, UI, good first issue
