### ISSUE TITLE
Unchecked "Do not ask again" does not work

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#566] opened 2022-05-20 14:50 UTC
1. Reset JabRef preferences
2. Restart JabRef
3. Start Import:\
    ![grafik](https://user-images.githubusercontent.com/1366654/200401582-c5d3803d-3011-44fd-824a-1a1a19c4bbc1.png)
4. Choose `metaData.pdf` from `src\test\resources\pdfs`
    ![grafik](https://user-images.githubusercontent.com/1366654/200401746-4e3a248f-7121-4742-a0f9-c6571a0b7b1f.png)
5. JabRef asks for "Remote services"
    ![grafik](https://user-images.githubusercontent.com/1366654/200401944-3d8157a8-1ceb-4f01-94ab-891f85c31a21.png)\
    ![grafik](https://user-images.githubusercontent.com/1366654/169553560-0fefc85c-6a86-472c-9996-862c2f8629dd.png)
9. Click "yes"
10. Cancel the import
    ![grafik](https://user-images.githubusercontent.com/1366654/200402105-08a9339a-0a09-4b64-bcfc-30594a126869.png)
12. Import the PDF again (steps 3 and 4)
13. Expected: Dialog appears. However, the PDF is parsed as is (and no dialog is appearing)\
    ![grafik](https://user-images.githubusercontent.com/1366654/200402272-d4d5e948-e914-4046-8552-df51ea9e894a.png)

**Comment by DunkDoge** [comment] 2022-10-20 08:32
Hi, can I work on this issue? I'm in a uni group and we've been tasked with contributing to open source software

**Comment by koppor** [comment] 2023-01-03 23:37
A huge discussion was going on at https://github.com/JabRef/jabref/pull/9291.

Preferences: Radio-Button-Group for Grobid: enable grobid, disable grobid, always ask for confirmation (source: https://github.com/JabRef/jabref/pull/9291#issuecomment-1306143262)

(No "DoNotAskAgain" button)

Open point: Link to privacy statement.

**Comment by hanachaari** [comment] 2023-02-11 14:25
Hi everyone ! I want to work on this issue.

**Comment by hanachaari** [comment] 2023-03-13 16:44
I am changing Gorbid preferences section into a radio-button-group. But the text property could not be resolved.
![image](https://user-images.githubusercontent.com/76585922/224761335-ad97b5c6-dfd5-4d10-96e3-e63d324bf35b.png)
I tried to add new labels, but I could not find the right folder in the project.

**Comment by koppor** [comment] 2023-03-22 09:50
You are working on strings shown to the user. These strings are also localized, because JabRef supports localization. Please read on at <https://devdocs.jabref.org/code-howtos/localization.html> for that topic. I think, this will help you to resolve the issue.

**Comment by hanachaari** [comment] 2023-03-22 11:37
The link was helpful. I added the strings to "JabRef_en.properties" and the problem was resolved.

**Comment by hanachaari** [comment] 2023-04-23 13:42
I have solved the issue and proceeded to create a merge request. So first I pulled the changes made in the origin repo (https://github.com/JabRef/jabref) and incorporated them into my repository. Without modifying any code I tried to run it but had an error in a file I never checked before.
![image](https://user-images.githubusercontent.com/76585922/233843012-1b3b4c50-f80f-406b-9400-cf417743b822.png)
Shouldn't it run without errors when first pulled from the main branch of the origin repository?

**Comment by hanachaari** [comment] 2023-04-24 22:09
I want to confirm that we will omit the "do not ask again" checkbox as mentioned in this comment https://github.com/koppor/jabref/issues/566#issuecomment-1370332527 . From a UX perspective, it would be better to keep it.

**Comment by koppor** [comment] 2023-04-27 07:01
Question answered at https://github.com/JabRef/jabref/pull/9801#issuecomment-1524050565.

**Comment by hanachaari** [comment] 2023-04-28 16:34
I have updated my branch with commits and updates made in the original repository . When I run it, I had this error.
![image](https://user-images.githubusercontent.com/76585922/235201792-9fea10a9-6c12-4247-8f6b-e958fcc86c15.png)
I checked the imported files, indeed they don't exist in "src\main\java\org\jabref\logic\exporter\ModsExporter.java" 
![image](https://user-images.githubusercontent.com/76585922/235203842-d8d31c56-3f8d-43be-b1bd-6c2e90208961.png)
but rather in src-gen\main\java\org\jabref\logic\importer\fileformat\mods
![image](https://user-images.githubusercontent.com/76585922/235203910-5fa6929c-3900-4493-921c-7c6cc83b2851.png)

**Comment by koppor** [comment] 2023-04-28 23:29
Execute "clean" and then "classes" task in gradle:

![image](https://user-images.githubusercontent.com/1366654/235269497-f93694af-a113-48c1-a58e-bf8dafb7ddaf.png)

**Comment by SUPWEZZ** [comment] 2023-10-19 13:53
Hi, I would like the work on the issue, please assign it to me if possible!

**Comment by colinldbd** [comment] 2023-10-20 06:08
Hi, is this issue be worked on? If not, can you please assign this issue to me? I'm a new contributor and learning how to contribute to open source projects.

**Comment by koppor** [comment] 2023-10-20 07:37
@SUPWEZZ This time, you were quicker than @colinldbd, so I assign @SUPWEZZ

**Comment by koppor** [comment] 2023-10-20 07:39
@SUPWEZZ This is a really hard issue, because it is not that much about implementation, but understanding what the current request is. Please go through the discussions, especially https://github.com/JabRef/jabref/pull/9801#issuecomment-1524050565

Maybe, it would help to create a [MADR](https://adr.github.io/madr/) document for the options to structure the possibilities.

**Comment by SUPWEZZ** [comment] 2023-10-24 14:44
Hi @koppor, sorry about that I'm a little confused. I just noticed I was being unassigned in two issues, but I would like to request one issue. I would like to ask compare it with "Import by id: cancel doesn't really cancel the request #10508" and "uncheck Do not ask again" Which issue is more suitable for beginners?

**Comment by koppor** [comment] 2023-10-24 21:09
@SUPWEZZ Based on the comment at https://github.com/JabRef/jabref/issues/10569#issuecomment-1777864845, I assign you here. - Not that **I** did not an unassignment, you can choose whatever you want. The only condition is that the issue is not already assigned to someone else.

Now, please focus on this one. Follow my recommendation at https://github.com/koppor/jabref/issues/566#issuecomment-1772238345, which I gave you 5 days ago.

**Comment by arshchawla21** [comment] 2024-10-14 03:04
Hello Maintainers, I am a second year CS major who would love to opportunity to take on this issue! I have been able to successfully reproduce the problem, and have also spent time analysing previous work on the topic.

**Comment by koppor** [comment] 2024-10-14 03:21
@arshchawla21 Thank you for choosing this task. I assigned you and I am looking forward to your contribution!

**Comment by ThiloteE** [comment] 2024-11-15 07:29
I suppose this issue was fixed by https://github.com/JabRef/jabref/pull/12034?
Closing then.

**Closed by ThiloteE** 2024-11-15 07:29 UTC
Labels: bug, good first issue, small
