### ISSUE TITLE
NPE when using SpringerFetcher

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#104] opened 2015-12-10 08:17 UTC
When searching Springer for "An Ontological Approach to Oracle BPM". Selecting that entry only and pressing "OK", an NPE occurs.

Also happens when importing http://link.springer.com/export-citation/chapter/10.1007/978-3-642-29923-0_30.bib using `--import-to-open`.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: field value must not be null
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.sf.jabref.model.entry.BibtexEntry.setField(BibtexEntry.java:329)
	at net.sf.jabref.gui.EntryMarker.unmarkEntry(EntryMarker.java:131)
	at net.sf.jabref.gui.ImportInspectionDialog$OkListener.actionPerformed(ImportInspectionDialog.java:740)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
```

![grabbed_20151210-091642](https://cloud.githubusercontent.com/assets/1366654/11710338/bd43215c-9f1e-11e5-984b-c7fbd9818a69.png)

Maybe @lenhard (because of 720b2d867decb001fb78a9548fd13839c4f4892f) and @oscargus (because of https://github.com/JabRef/jabref/pull/291)

Should that be covered by a test case somehow?

**Comment by lenhard** [comment] 2015-12-10 09:57
Yes, this is propably due to those changes. 

However, the problem is not `BibtexEntry`, but in `EntryMarker`. Why is it trying to a null on a `BibtexEntry`? Some minimal parameter validation in `EntryMarker` should be sufficient.

**Comment by tobiasdiez** [comment] 2015-12-10 10:02
I think line 131 should be replaced by 
```` java
if(newValue == null)
   be.clearField(BibtexFields.MARKED);
else
   be.setField(BibtexFields.MARKED, newValue);
````

**Comment by lenhard** [comment] 2015-12-10 10:11
Done in https://github.com/JabRef/jabref/commit/3f843c698bb37834b920eb9d3bd485d92571e153

@koppor, please confirm if this fixes the issue.

**Comment by oscargus** [comment] 2016-02-02 10:08
I tried this now and it works, so I close this.

**Closed by oscargus** 2016-02-02 10:08 UTC
