### ISSUE TITLE
When JabRef is started, load the library in the folder of `JabRef.bat`

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#377] opened 2019-11-21 20:11 UTC
- If there is no previously opened library in JabRef AND
- If a single `bib` file exists in the startup directory of JabRef

THEN: this should be opened (use case: portable jabref used in a research group)

**Comment by K5qu4r3d** [comment] 2023-04-07 02:03
@koppor I'd like to take a look into this issue. I presume this is still part of the larger JabRef project issues list even though this one is among the issues list of your fork.

I have a couple of questions.
- What determines the startup directory of JabRef?
- `JabRef.bat` is located in the `runtime/bin/` directory as of the latest development version. Considering that directory is entirely code compilation (?) files, should one be saving/loading files to/from there?

**Comment by koppor** [comment] 2023-04-07 14:28
Kevin, thank you for choosing JabRef. This issue is a one where not much code is to be written, but much experiments being done. Please choose this issue only if you intend to contribute more to JabRef. Or if you intend to keep working in the Java space. If not, I would recommend to switch to another issue.

Idea of the issue: JabRef is not installed globally, but as portable version

Reproduce the idea:

1. Go to https://builds.jabref.org/main/
2. Download the Windows portbale zip file (currently, this is https://builds.jabref.org/main/JabRef-5.10-portable_windows.zip)
3. Create directory c:\temp\377
4. Extract the zip-file into that directory
5. Check that the result is as follows\
   ![image](https://user-images.githubusercontent.com/1366654/230621337-86d0493c-91ac-4477-904b-bb4f8d159064.png)
6. Create a file `demo.bib`
  1. ![image](https://user-images.githubusercontent.com/1366654/230621414-947bf67d-1052-4e67-8cd0-c56af61c41a8.png)
  2. Rename file by selecting it, pressing <kbd>F2</kbd>
  3. ![image](https://user-images.githubusercontent.com/1366654/230621485-5ce1a3cf-8714-4382-8e66-7b301aff0b65.png)
  4. And then typing "test.bib" and deleting `.txt`
7: Check that that file exists: \
   ![image](https://user-images.githubusercontent.com/1366654/230621584-2365be92-d287-42aa-bd25-46715eb7aced.png)
8. Note that creating `test.bib` can be done in another way. In my case, I enabled showing the file extensions in Windows Explorer. That way, it was easy for me to replace `.txt` by `.bib? 

Now, start JabRef by double clicking the .exe. JabRef should start.

Now, you need to make a modified version of JabRef:

1. Go to [/src/main/java/org/jabref/cli/Launcher.java#L49](https://github.com/JabRef/jabref/blob/0111d5987d71d03fe768149d8d5d25bf6fdfab36/src/main/java/org/jabref/cli/Launcher.java#L49)
2. Add `System.out.pritnln("Current directory " + Path.of("").toAbsolutePath().toString())`; (inspired from https://stackoverflow.com/a/51028045/873282)
3. Prepare a portable zip file by the gradle `jlinkZip` task
   ![image](https://user-images.githubusercontent.com/1366654/230622569-710462d3-e099-4b62-85b3-e9b62a3fecfa.png). Will take a long time. Here, it was 4 minutes. Ignore the warnings.
4. Now execute `jpackage`
5. Then, in the folder `build\distribution\JabRef`, you will find the `.exe`
6. Open a CMD.exe and run it
7. See that nothing is output
8. Then see that there is a logger initialized
9. Add logging at this place (instead of System.out.println) to have the output appearing in `log.txt` (howto at https://devdocs.jabref.org/code-howtos/logging.html)

Step 9 will teach you how logging works (how to configure it, where to find `log.txt`, ...)

**Comment by K5qu4r3d** [comment] 2023-04-08 18:58
Understood. Given what you mentioned, and given that the "Good First Issues" tag was removed from this issue, it seems best for me to look at other ones - I _do_ want to contribute more to JabRef and further my Java experience.

Also, on the error reproducing steps, when I get past this step...

> Add logging at this place (instead of System.out.println) to have the output appearing in log.txt

...and run `JabRef.exe` after repeating steps 3) through 6) above it, I get this error:

![image](https://user-images.githubusercontent.com/25234451/230738304-8e1c06e3-0157-4cfe-9f5f-2133968294ef.png)

**Comment by koppor** [comment] 2023-04-08 23:27
Kevin, this is a good first issue to step into the build process. - I removed the label "good first issue", because it is no real quick win. You are very invited to continue to learn about the Java eco system.

The next step would be: Checkout `main` branch - and create a portable app based on that. Does that `.exe` from that distribution run?

In case you are familiar with a debugger, working on https://github.com/JabRef/jabref/issues/9738 could also be nice.

**Comment by K5qu4r3d** [comment] 2023-04-14 02:34
> Kevin, this is a good first issue to step into the build process.

Okay. I'm more than happy to continue working on this as much as I can.

> The next step would be: Checkout `main` branch - and create a portable app based on that. Does that .exe from that distribution run?

So turns out I was doing the reproducing steps on the `main` branch (instead of a separate one) and made a few changes to `Launcher.java` and `tinylog.properties` 😅

I've since shelved those changes and updated the branch with the latest changes.

Anyway, after running `jlinkZip` and `jpackage` from the `main` branch, the `.exe` from this distribution successfully runs and the app loads.

> In case you are familiar with a debugger, working on [JabRef#9738]( https://github.com/JabRef/jabref/issues/9738) could also be nice.

I'll take a look.

**Comment by jiaxin0103** [comment] 2024-10-14 04:44
Hello, I am a student at the Australian National University. For our team project, we need to contribute to an open-source project. May I be assigned to this task?

**Comment by koppor** [comment] 2024-10-14 05:04
@jiaxin0103 Sure. Please be aware this is more than Java coding, you need to build a portable distribution of JabRef to test.

**Comment by koppor** [comment] 2024-11-13 00:13
@jiaxin0103 I was wrong, it was more a thing of coding 91 lines of code needed. - I implemented at https://github.com/JabRef/jabref/pull/12172/files

**Closed** 2024-11-13 19:26 UTC
Labels: feature
