### ISSUE TITLE
When pasting a .bib entry, the new entry should be focused in the entry editor

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#555] opened 2021-12-23 10:54 UTC
Example:

Paste

```bibtex

@phdthesis{,
    author = {Braun, Felix},
    title = {Application of algorithm-based validation tools for the validation of complex, multi-variant products},
    editor = {},
    booktitle = {},
    series = {},
    journal = {},
    address = {},
    publisher = {},
    edition = {},
    year = {2021},
    isbn = {},
    volume = {},
    number =  {},
    pages = {},
    url = {},
    doi = {},
    keywords = {variant-oriented product portfolios; portfolio validation; portfolio verification; multi-variant products; boolean rules; algorithm-based validation tools},
    abstract = {Based on trends like mass-customization and the individualisation of mass products also in the vehicle manufacturing industry, multi-variant product portfolios are usually required to account for all the necessary variance. As this work is based on a research cooperation between university and a large commercial vehicle manufacturer, such types of a product portfolio are closely observed. In these types of product portfolios, large sets of Boolean portfolio rules are used to describe the product portfolio with all its variants. In the same time, numerous departments within engineering, sales and production work on these portfolio rules with different information flows and perspectives. Therefore, it is difficult to maintain a fully valid and consistent state of the portfolio over time. This is especially challenging, as advanced tools and algorithms are necessary to ensure validity, as the amount of rules and interdependencies is too large to be handled manually in complex product portfolios. This research examines the different types of multi-variant product portfolio descriptions and its requirements regarding validity and consistency described in recent literature. Based on the definition of how validity is reached within a portfolio, existing approaches on how to ensure this validity over time are explained. Taking these findings into account, the current gap in research is identified: neither exists a concise definition of portfolio validity, nor is an integral approach or process presented to ensure validity in the practical application. Therefore, this research proposes a concise definition of the requirements leading to validity within complex, multi-variant product portfolios. Based on these requirements, an integral approach, a procedural model, is proposed to achieve and maintain validity within complex, multi-variant product portfolios. This approach is explained in detail in the main section of this work. This procedural model is implemented in a real-world industry example in the form of a case study jointly executed with the industry partner. In this case study, a fully valid state of the product portfolio, according to the predefined requirements, can be achieved. Hereby, both the applicability and the validity of the proposed procedural model are shown. Finally, the main findings are outlined: a generic data model and documentation logic for complex, multi-variant product portfolios exist. On this basis, general requirements on the validity of a product portfolio definition can be stated. With the help of existing validation tools and algorithms, a procedural model can be used to guide and structure the validation process of the portfolio rules. When this process is being followed, a fully valid state of the product portfolio and its rules can be reached.  This work also helps the industry partner in the commercial vehicle industry to structure and perform its portfolio validation process as part of its daily business.},
    note = {},
    
    school = {Universität der Bundeswehr München},
    
}
```

The entry is created, but not selected in th emain table or entry editor

**Comment by 0x002A** [comment] 2022-06-22 21:54
I tried to reproduce this one but in my case the imported enry is indeed focused.
Please describe more precisely.

**Comment by PaluTheBear** [comment] 2022-12-23 16:31
I also could not reproduce.

**Comment by ThiloteE** [comment] 2023-01-20 16:13
closing this issue and most importantly removing this from "good first issues", as 3 people tried to reproduce and could not.

**Closed by ThiloteE** 2023-01-20 16:13 UTC
Labels: feature, good first issue, small
