### ISSUE TITLE
Refactor OpenDatabaseAction class

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#26] opened 2015-11-19 09:00 UTC
The loadDatabase() method shouuld be moved to another place. The OpenDatabaseAction class contains quite a lot of gui stuff while this method is purely logic.

See [PR 361](https://github.com/JabRef/jabref/pull/361) for details.

**Comment by simonharrer** [comment] 2015-11-25 13:20
:+1:

**Comment by koppor** [comment] 2023-06-21 18:56
Duplicate of https://github.com/JabRef/jabref/issues/8298

**Closed by koppor** 2023-06-21 18:56 UTC
