### ISSUE TITLE
Code: Use more Optionals

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#116] opened 2016-01-26 12:02 UTC
For example, in
`BibDatabase.getResolvedField: database`

**Comment by oscargus** [comment] 2016-02-01 10:51
I agree it is a good idea!

**Comment by simonharrer** [comment] 2016-05-10 14:03
Duplicate of https://github.com/JabRef/jabref/issues/1154

**Closed by simonharrer** 2016-05-10 14:03 UTC
