### ISSUE TITLE
When opening a library and a .bak file is found -> show the diff

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#391] opened 2020-01-19 22:21 UTC
Instead of just asking to load the backup, show the diff to the backup.

Use the file conflict dialog (appears when a file is changed externally).

**Comment by koppor** [comment] 2020-03-13 19:16
If there is no diff, the dialog should not be shown.

**Comment by koppor** [comment] 2021-03-30 12:32
Still happening on today's main build:

![grafik](https://user-images.githubusercontent.com/1366654/112989011-c272e980-9164-11eb-83ff-c902629dc082.png)

**Comment by Siedlerchr** [comment] 2022-09-15 16:50
The merge dialog should now be shown. 
There needs to be warning as well:

WARNING: Restore from backup will overwrite your current library

**Comment by Siedlerchr** [comment] 2022-09-15 16:55
Duplicate of https://github.com/JabRef/jabref/issues/9066

**Closed by Siedlerchr** 2022-09-15 16:55 UTC
Labels: good first issue
